Initial_products = [
    {
        'name': 'Veg Roll',
        'product_id': 1,
        'available_stocks': 10,
        'price_per_unit': 30,
        'tax_percentage': 5,
    },
    {
        'name': 'Veg Patty Burger',
        'product_id': 2,
        'available_stocks': 10,
        'price_per_unit': 80,
        'tax_percentage': 5,
    },
    {
        'name': 'Veg Cheese Pizza',
        'product_id': 3,
        'available_stocks': 10,
        'price_per_unit': 120,
        'tax_percentage': 5,
    },
    {
        'name': 'Mushroom Roll',
        'product_id': 4,
        'available_stocks': 10,
        'price_per_unit': 50,
        'tax_percentage': 5,
    },
    {
        'name': 'Mushroom Patty Burger',
        'product_id': 5,
        'available_stocks': 10,
        'price_per_unit': 100,
        'tax_percentage': 5,
    },
    {
        'name': 'Mushroom Cheese Pizza',
        'product_id': 6,
        'available_stocks': 10,
        'price_per_unit': 140,
        'tax_percentage': 5,
    },
        {
        'name': 'Panner Roll',
        'product_id': 7,
        'available_stocks': 10,
        'price_per_unit': 80,
        'tax_percentage': 5,
    },
    {
        'name': 'Panner Patty Burger',
        'product_id': 8,
        'available_stocks': 10,
        'price_per_unit': 130,
        'tax_percentage': 5,
    },
    {
        'name': 'Panner Cheese Pizza',
        'product_id': 9,
        'available_stocks': 10,
        'price_per_unit': 170,
        'tax_percentage': 5,
    },
    {
        'name': 'Tea',
        'product_id': 10,
        'available_stocks': 100,
        'price_per_unit': 10,
        'tax_percentage': 5,
    },
    {
        'name': 'Coffee',
        'product_id': 11,
        'available_stocks': 100,
        'price_per_unit': 150,
        'tax_percentage': 5,
    },
    {
        'name': 'Milk',
        'product_id': 12,
        'available_stocks': 50,
        'price_per_unit': 8,
        'tax_percentage': 5,
    }
]
