# Generated by Django 6.0.3 on 2026-04-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_net_price_bill_total_tax_bill_total_without_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='deno_object',
            field=models.JSONField(default=dict),
        ),
    ]
